apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/acm-workshop/sockshop-ws:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/acm-workshop/sockshop-ws:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: sockshop-ws
        chartPath: charts/sockshop-ws
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/acm-workshop/sockshop-ws"
          image.tag: "{{.TAG}}"
