---
groups:
- name: front-end-jobs
  jobs:
  - build-front-end
  - deploy-front-end-to-stage
  - health-check
  - deploy-front-end-to-prod
  - execute-front-end-load-tests
  - validate-front-end-load-test
  - promote-new-version-front-end
  - upload-front-end-git-release

- name: init-dynatrace
  jobs: 
  - init-dynatrace-front-end

resource_types:
- name: dynatrace-resource
  type: docker-image
  source:
    repository: mvilliger/dynatrace-resource

resources:

#GitHub Release Repository
- name: front-end-release
  type: github-release
  source:
    owner: acm-workshop-concourse
    repository: front-end
    access_token: ((github-access-token))

# GitHub Repositories
- name: git-pipeline
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/sockshop.git

- name: git-jmeter-as-container
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/jmeter-as-container.git

- name: git-front-end
  type: git
  source:
    branch: master
    uri: https://github.com/((workshop-repository))/front-end.git

- name: dynatrace
  type: dynatrace-resource
  source:
    apitoken: ((apitoken))
    tenanthost: ((tenanthost))

- name: front-end-release-bucket
  type: s3
  source:
    region_name: eu-west-1
    regexp: front-end/front-end-(.*).tar
    bucket: ((s3-bucket))
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))

- name: version
  type: semver
  source:
    driver: git
    uri: https://github.com/((workshop-repository))/front-end.git
    branch: master
    file: version

# PCF Environments

- name: pcf-stage
  type: cf
  source:
    api: ((pcf-stage-api))
    username: ((pcf-stage-deploy-username))
    password: ((pcf-stage-deploy-password))
    organization: ((pcf-stage-organization))
    space: ((pcf-stage-space))
    skip_cert_check: false

- name: pcf-production
  type: cf
  source:
    api: ((pcf-prod-api))
    username: ((pcf-prod-deploy-username))
    password: ((pcf-prod-deploy-password))
    organization: ((pcf-prod-organization))
    space: ((pcf-prod-space))
    skip_cert_check: false

jobs:

# Initialize Dynatrace Custom Device

- name: init-dynatrace-front-end
  public: true
  plan:
  - aggregate:
    - get: git-pipeline
    - get: git-front-end 
  - task: init-dynatrace-task
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/init-dynatrace-task.yml
    params: 
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-front-end

# FRONT-END

- name: build-front-end
  plan:
  - get: git-front-end
    trigger: false
  - get: version
    params: { pre: build }
  - task: create-tarball
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: git-front-end
      - name: version
      outputs:
      - name: workspace
      run:
        path: /bin/sh
        args:
        - -exc
        - |
          output_dir=workspace
          cp git-front-end/server.js "${output_dir}/"
          tar -cf "${output_dir}"/front-end-$(cat version/number).tar "${output_dir}"/server.js
  - put: front-end-release-bucket
    params: 
      file: workspace/front-end-*.tar

- name: deploy-front-end-to-stage
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - build-front-end
  - get: git-pipeline
    trigger: false      
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-stage-front-end-suffix)) 
      APP_REPO: git-front-end           
  - put: dynatrace
    params:
      monspecserviceenvironment: front-end/Staging
      pipelinetaskname: deploy-front-end-to-stage
      deployversion: v1.0
      APP_REPO: git-front-end
  - put: pcf-stage
    params:
      path: git-front-end
      manifest: app-manifest-output/manifest.yml

- name: health-check
  serial: true
  public: true
  plan:
  - aggregate:
    - get: git-front-end
      trigger: true
      passed:
        - deploy-front-end-to-stage
    - get: git-jmeter-as-container
    - get: git-pipeline
  - task: run-health-check
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/health-test.yml
    params:
      APP_REPO: git-jmeter-as-container
      FUNC_VALIDATION: yes
      PRODUCTION: false
      SCRIPT_NAME: basiccheck.jmx
      PCF_APP_SUFFIX: ((pcf-stage-front-end-suffix))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))
      DT_LTN: HealthCheck
      VUCount: 1
      LoopCount: 1

- name: deploy-front-end-to-prod
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - health-check
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))   
  - task: prepare-app-manifest
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/app-manifest-prep.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix)) 
      APP_REPO: git-front-end
      PRODUCTION: true                 
  - put: dynatrace
    params:
      monspecserviceenvironment: front-end/Production
      pipelinetaskname: deploy-front-end-to-prod
      deployversion: v1.0 
      APP_REPO: git-front-end 
  - put: pcf-production
    params:
      path: git-front-end
      manifest: app-manifest-output/manifest.yml

- name: execute-front-end-load-tests
  plan:
  - aggregate:
    - get: git-front-end
      trigger: true
      passed:
        - deploy-front-end-to-prod
#  - task: run-load-tests
#    config:
#      platform: linux
#      inputs:
#      - name: git-front-end
#      run:
#        dir: git-front-end
#        path: /bin/bash
#        args:
#        - -exc
#        - |
#          yarn install
#          bash test/e2e/runner.sh

- name: validate-front-end-load-test
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - execute-front-end-load-tests
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))       
  - task: validate-via-monspec
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/validate-via-monspec.yml
    params: 
      monspeccomparison: front-end/Production-$NEXT_APP_COLOR\ToProduction-$CURRENT_APP_COLOR\Last5m
      apitoken: ((apitoken))
      tenanthost: ((tenanthost))
      APP_REPO: git-front-end

- name: promote-new-version-front-end
  serial: true
  public: true
  plan:
  - get: git-front-end
    trigger: true
    passed:
      - execute-front-end-load-tests
  - get: version
    params: { bump: patch }
  - get: git-pipeline
    trigger: false      
  - task: get-current-app-color
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/current-app-get-info.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))   
  - task: switch-app-routes
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/update-routes.yml
    params:
      PCF_APP_SUFFIX: ((pcf-prod-front-end-suffix))
      PCF_API: ((pcf-prod-api))
      PCF_ORG: ((pcf-prod-organization))
      PCF_USER: ((pcf-prod-deploy-username))
      PCF_PWD: ((pcf-prod-deploy-password))
      PCF_SPACE: ((pcf-prod-space))
      PCF_APP_DOMAIN: ((pcf-prod-app-domain))

- name: upload-front-end-git-release
  public: true
  plan:
  - aggregate:
    - get: git-front-end
      trigger: true
      passed: 
        - promote-new-version-front-end
    - get: front-end-release-bucket
    - get: git-pipeline
    - get: version
      params: { pre: build }
  - task: create-front-end-release-info
    file: git-pipeline/deploy/cloud-foundry/ci/tasks/prepare-release.yml
    params:
      APP_NAME: front-end
  - put: front-end-release
    params:
      name: prepared-release/name
      tag: prepared-release/tag
#      globs:
#      - front-end-release-bucket/front-end-*.jar
#  - put: version
#    params: { file: version/number }